import MediaPage, { RelatedMedia } from './MediaPage'
import PresentationRecord from './PresentationRecord'
import { presentations, eventPresentations, outreachPresentations, presentationYears, presentationScope } from './presentationData'
import { useEffect, useState, type ReactNode } from 'react'
import { MagnifyingGlass, DownloadSimple, ArrowLeft, } from '@phosphor-icons/react'
import { imageAssets, type ImageAsset } from './siteContent'
import { portfolioCollections, portfolioItemCount, type PortfolioCollection } from './portfolioContent'
import { careerTimeline, cvPath, studies } from './expandedContent'
import photos from './personalPhotos.json'
import bibliography from './bibliography.json'
import ResearchExplainer from './ResearchExplainer'
import SoftwareShowcase from './SoftwareShowcase'

const publicationOrder = ['brain-followup','ethos-2025','amos-2025','biophysics-2020']
const publicationStudies = ['brain-metastases-follow-up','radiosurgery-planning','organ-segmentation','amyloid-membranes']
const sortedBibliography = [...bibliography].sort((a,b)=>publicationOrder.indexOf(a.id)-publicationOrder.indexOf(b.id))
const recordId = (group: number, item: number) => `entry-${group}-${item}`
function SourceLink({ href, children }: { href: string; children: ReactNode }) { return <a className="source-link" href={href}>{children}</a> }
function PagePhoto({ asset, caption, className = '' }: { asset: ImageAsset; caption: string; className?: string }) { return <figure className={`page-photo ${className}`}><img src={asset.src} alt={asset.alt} width="1000" height="750" loading="lazy" /><figcaption>{caption}{asset.source && <> · <a href={asset.source}>Source</a></>}</figcaption></figure> }
function PageIntro({ eyebrow, title, children }: { eyebrow: string; title: ReactNode; children: ReactNode }) { return <div className="page-intro wrap"><a className="back-link" href="/"><ArrowLeft /> Home</a><span className="meta page-eyebrow">{eyebrow}</span><h1>{title}</h1><div className="page-lede">{children}</div></div> }
function SectionNav({ items }: { items: { id: string; label: string }[] }) { return <nav className="section-nav wrap" aria-label="On this page"><span>On this page</span>{items.map(i => <a href={`#${i.id}`} key={i.id}>{i.label}</a>)}</nav> }
export function CVLink({ className = 'button' }: { className?: string }) { return <a className={className} href={cvPath} download="Udbhav_Ram_Public_CV_October_2026.pdf"><DownloadSimple /> Download public CV <span className="pdf-label">PDF</span></a> }
export function LatestWork() { return <aside className="latest-work wrap"><div><span className="meta">September 29, 2026 · ASTRO, Boston</span><h2>Fresh from <em>ASTRO 2026.</em></h2></div><div><p>How much does a treatment target change between observers? My latest poster studies contouring uncertainty across clinical specialties in online adaptive partial-breast irradiation.</p><a className="text-link" href="/research/adaptive-breast-radiotherapy">Explore the study</a></div></aside> }
export function ExploreMore() { return <section className="explore-more wrap section" id="recognition"><div className="section-heading"><h2>A few more<br /><em>threads to follow.</em></h2><p>The full story, from the newest research to the projects, people, and experiences that came before.</p></div><div className="explore-links">{[
  ['/about', '01', 'Biography & CV', 'The path from McMaster and UAB to Wisconsin.'],
  ['/publications', '02', 'Publications & talks', 'Papers, posters, presentations, and source material.'],
  ['/software', '03', 'Software & building', 'Open research tools, engineering, and experiments.'],
  ['/media', '04', 'Media & stories', 'Profiles, conversations, and videos from work and life.'],
  ['/beyond', '05', 'Beyond the lab', 'Motorsport, music, diving, and the other parts of life.'],
  ['/collection', '06', 'The collection', `${portfolioItemCount} records, organized and searchable.`],
].map(([href, n, title, text]) => <a href={href} key={href}><span className="meta">{n}</span><h3>{title}</h3><p>{text}</p></a>)}</div><div className="cv-home"><CVLink /><span>Updated October 2026 · Public-facing edition</span></div></section> }

function AboutPage() { return <>
  <PageIntro eyebrow="Biography & curriculum vitae" title={<>A life shaped<br />by <em>curiosity.</em></>}><p>I’m Udbhav Ram, or Udi. I’m a Medical Physics PhD student at the University of Wisconsin–Madison, working with Dr. Ran Zhang. My path brings together clinical research, software, motorsport, and teaching.</p><div className="intro-actions"><CVLink /><a className="text-link" href="/collection/profile-foundations">Explore the earlier record</a></div><small>Public CV · Updated October 2026</small></PageIntro>
  <SectionNav items={[{id:'biography', label:'Biography'}, {id:'timeline',label:'Education & experience'}, {id:'mentorship',label:'Mentorship & service'}, {id:'recognition-about',label:'Recognition'}]} />
  <section className="wrap editorial-split detail-section" id="biography"><PagePhoto asset={imageAssets.heroPortrait} caption="At McMaster University" /><div className="prose"><h2>Physics, with<br /><em>people in view.</em></h2><p>My research sits where medical images, computational tools, and clinical decisions meet. I work on questions in image segmentation, radiation treatment planning, adaptive radiotherapy, and AI-assisted workflows.</p><p>My connection with McMaster began before my undergraduate degree. Mentorship from Ben Davis-Purcell gave me the chance to sit in on physics courses and meet my first research supervisor. I began research work in 2019, before starting my degree in 2021.</p><p>I studied Honours Medical Physics with Co-op at McMaster University. A research collaboration with Dr. Carlos Cardenas at the University of Alabama at Birmingham (UAB) began remotely in 2021 and grew into an eight-month visiting-scholar placement in radiation oncology in 2024. I returned to Birmingham for a second co-op in 2025.</p><p>That work has included physician-reviewed organ segmentation, single-isocenter radiosurgery planning, local language models for naming quality assurance, and contouring uncertainty in adaptive breast treatment. My doctoral chapter at Wisconsin continues the connection between AI, imaging, and cancer care, including an interest in vision-language models for medical imaging and radiation oncology.</p><p>There’s an engineering thread too: race strategy at Arrow McLaren, vehicle controls with Formula SAE, robotics, full-stack software, and hands-on fabrication. You can explore those projects alongside the research, rather than as a footnote to it.</p><p>Outside work, I ride horses, play music, and dive. I hold PADI Advanced Open Water Diver and Enriched Air Diver (Nitrox) qualifications, confirmed in 2025.</p><a className="text-link" href="/beyond#outdoors">Life outside the lab</a><SourceLink href="https://amportal.astro.org/udbhav-ram-bs-135368427">Current research biography</SourceLink></div></section>
  <section className="wrap detail-section" id="timeline"><div className="section-heading"><h2>Chapters<br /><em>along the way.</em></h2><p>Education and selected experience. Parallel research, engineering, and community work have often overlapped.</p></div><ol className="career-timeline">{careerTimeline.map(x => <li key={x.title}><span className="timeline-date">{x.date}</span><div><span className="meta">{x.place}</span><h3>{x.title}</h3><p>{x.text}</p><SourceLink href={x.source}>Read the source</SourceLink></div></li>)}</ol><div className="quiet-callout"><p>More research affiliations include Hamilton Health Sciences / Juravinski Cancer Centre, Western University / Lawson Health Research Institute, the Hamilton Centre for Kidney Research, and McMaster’s Laboratory for Membrane and Protein Dynamics.</p><a href="/collection/research-record">Explore the research history</a></div></section>
  <section className="detail-band" id="mentorship"><div className="wrap editorial-split"><div className="prose"><span className="meta">Mentorship, advocacy & service</span><h2>Opening doors<br /><em>for other people.</em></h2><p>The UAB–McMaster relationship became more than a research placement. As an undergraduate ambassador, I helped connect students and faculty across the institutions and shared the experience with students considering their own path.</p><p>My undergraduate-era role as a Mary Heersink Institute for Global Health Trainee Scholar included student outreach, information sessions, and helping coordinate the McMaster Spring Symposium and UAB–McMaster Summer Program. As a Science Co-op mentor, I helped students navigate job searches, resumes, interviews, and international placements.</p><p>My earlier community work includes lead mentorship with Robotique Zone01, programming and outreach with FIRST Robotics Competition Team 4939, and French-language STEM program coordination with Sparkin’ STEM.</p><p>I’ve also volunteered across medical imaging, surgical inpatient, and information services at Humber River Hospital, and taught yoga in community and university settings. My science-policy work includes the Journal of Science Policy & Governance’s 2023 ambassador cohort.</p><div className="inline-links"><a href="https://www.sciencepolicyjournal.org/ambassadors.html">Science-policy ambassadorship</a><a href="/collection/activities-service">Activities & service record</a><a href="https://www.uab.edu/medicine/news/latest-news/mcmaster-student-and-mentor">The UAB collaboration story</a></div></div><PagePhoto asset={imageAssets.uabMentor} caption="Research and mentorship at UAB" /></div></section>
  <section className="wrap detail-section" id="recognition-about"><div className="section-heading"><h2>Recognition<br /><em>and community.</em></h2><p>Selected milestones, with the full historical record available to explore.</p></div><div className="recognition-list"><article><span className="meta">2026 · McMaster University</span><h3>Science Co-op Student of the Year</h3><p>Recognized as the Year 5 recipient. My UAB supervisors travelled from Alabama for the presentation.</p><SourceLink href="https://news.mcmaster.ca/udbhav-rams-co-op-supervisors-flew-in-from-alabama-to-give-him-an-award/">Read the McMaster story</SourceLink></article><article><span className="meta">2025 · AAPM</span><h3>Blue Ribbon Poster</h3><p>Research on locally hosted language models for radiation-oncology nomenclature and quality assurance.</p><a href="/research/clinical-language-models">Explore the research</a></article><article><span className="meta">2024 · SPS / AAPM</span><h3>Outstanding Poster Presentation</h3><p>Undergraduate research recognition for the Ethos high-fidelity radiosurgery-planning work.</p><a href="/collection/recognition">All recognition & historical credentials</a></article></div></section>
<RelatedMedia path="/about" />
</> }

function ResearchPage() { return <>
  <PageIntro eyebrow="Research" title={<>From an image<br />to a <em>clinical question.</em></>}><p>Medical image segmentation, treatment planning, adaptive radiotherapy, and clinical AI. Each project starts with a specific question and keeps its methods, findings, and limitations in view.</p><div className="intro-actions"><a className="button" href="/publications">Publications & talks</a><a className="text-link" href="/software">Research software</a></div></PageIntro>
  <div className="detail-band research-explainer-band"><div className="wrap"><ResearchExplainer /></div></div>
  <div className="wrap research-index">{studies.map((s,i) => <article className={`study-index-row ${i===0 ? 'study-newest':''}`} key={s.slug}><PagePhoto asset={s.image} caption={s.caption} /><div><span className="meta">{s.year} · {s.status}</span><h2><a href={`/research/${s.slug}`}>{s.title}</a></h2><p>{s.intro}</p><a className="text-link" href={`/research/${s.slug}`}>Read the case study</a></div></article>)}</div>
  <section className="wrap detail-section"><div className="section-heading"><h2>Earlier questions,<br /><em>lasting threads.</em></h2><p>The research record also includes optical brain measurement, smartphone gel-electrophoresis analysis, augmented reality for surgical models, genomic radiation-dose modelling, and early biophysics.</p></div><a className="button" href="/collection/research-record">Browse the research collection</a></section>
  <RelatedMedia path="/research" />
</> }
function StudyPage({ slug }: { slug: string }) { const s=studies.find(x=>x.slug===slug); if(!s) return <NotFound />; return <>
  <PageIntro eyebrow={`${s.year} · ${s.status}`} title={s.title}><p>{s.intro}</p></PageIntro>
  <div className="wrap study-title-line"><span>{s.subtitle}</span><a href="/research">All research</a></div>
  <div className="wrap study-layout"><aside className="study-sidebar"><div className="study-stats">{s.facts.map(f=><div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div><nav aria-label="Study sections">{s.sections.map((section,i)=><a href={`#study-section-${i}`} key={section.heading}>{section.heading}</a>)}<a href="#study-sources">Sources & further reading</a></nav></aside><article className="study-prose"><PagePhoto asset={s.image} caption={s.caption} className={s.slug==='clinical-language-models' ? 'poster-photo':''} />{s.sections.map((section,i)=><section className="prose" id={`study-section-${i}`} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<section className="prose source-box" id="study-sources"><h2>Sources & further reading</h2><ul>{s.sources.map(source=><li key={source.href}><a href={source.href}>{source.label}</a></li>)}</ul><p className="small-note">Research summary updated October 5, 2026. Findings describe the linked study and do not establish clinical readiness beyond its evaluation.</p></section></article></div>
  <section className="wrap related-strip"><h2>Keep exploring.</h2>{studies.filter(x=>x.slug!==s.slug).slice(0,2).map(x=><a href={`/research/${x.slug}`} key={x.slug}><span className="meta">{x.status}</span><h3>{x.title}</h3></a>)}</section>
<RelatedMedia path={`/research/${s.slug}`} />
</> }

function PublicationsPage() { return <>
  <PageIntro eyebrow="Publications & presentations" title={<>The work,<br /><em>on the record.</em></>}><p>Peer-reviewed articles, conference presentations, and posters. Conference work and exploratory software are kept distinct from published journal articles.</p><div className="intro-actions"><CVLink /><a className="text-link" href="https://pubmed.ncbi.nlm.nih.gov/?term=Udbhav+S+Ram">PubMed author search</a></div></PageIntro>
  <SectionNav items={[{id:'journal-articles',label:'Journal articles'}, {id:'presentations',label:'Presentations & talks'}, {id:'outreach-presentations',label:'Outreach'}]} />
  <section className="wrap reading-width detail-section" id="journal-articles"><h2>Journal <em>articles.</em></h2><ol className="bibliography">{sortedBibliography.map((p,i)=><li key={p.id}><span className="bibliography-number">0{i+1}</span><div><span className="meta">{p.issue_date} · {p.journal} · {p.role}</span><h3><a href={p.url}>{p.title}</a></h3><p>{p.journal} {p.volume}({p.issue}), {'pages' in p ? p.pages : p.article_number}. DOI: {p.doi}</p><details className="citation-details"><summary>Authors & publication dates</summary><p>{p.authors.join(', ')}.</p><p>First published online {p.online_date}. Journal issue: {p.issue_date}.</p></details><SourceLink href={p.url}>Publication record</SourceLink><a className="source-link" href={`/research/${publicationStudies[i]}`}>Read the case study</a></div></li>)}</ol></section>
  <section className="detail-band" id="presentations"><div className="wrap reading-width"><span id="recent-presentations" /><span id="earlier-presentations" /><h2>Presentations<br /><em>& talks.</em></h2><div className="presentation-summary"><p>{presentationScope}</p><p>Conference listings, recorded work, and delivered talks are distinguished below. The named presenter may be a collaborator.</p><a className="text-link" href="/collection?topic=presentations">Search all presentation records</a></div><nav className="section-nav" aria-label="Presentation years">{presentationYears.map(year=><a href={`#presentations-${year}`} key={year}>{year}</a>)}</nav>{presentationYears.map(year=><section className="presentation-year" id={`presentations-${year}`} key={year}><h3>{year}</h3>{eventPresentations.filter(p=>p.year===year).map(p=><PresentationRecord key={p.id} presentation={p}/>)}</section>)}</div></section>
  <section className="wrap reading-width detail-section" id="outreach-presentations"><h2>Outreach<br /><em>& peer mentorship.</em></h2><p className="section-intro">An aggregate account, kept separate from individually dated conference and institutional events.</p>{outreachPresentations.map(p=><PresentationRecord key={p.id} presentation={p}/>)}</section>
<RelatedMedia path="/publications" />
</> }

function SoftwarePage() { return <>
  <PageIntro eyebrow="Software & engineering" title={<>Ideas become<br /><em>working things.</em></>}><p>Open research code, medical-physics tools, and engineering projects. The common thread is building systems that can be inspected, tested, and improved.</p><a className="button" href="https://github.com/udiram">Explore GitHub</a></PageIntro>
  <SoftwareShowcase />
  <section className="detail-band"><div className="wrap editorial-split"><div className="prose"><h2>Learning by<br /><em>building.</em></h2><p>Earlier projects include an automated prosthetic-hand prototype, a computer-vision recycling sorter, vehicle driver-assistance work using openpilot, and full-stack applications with mathematical and deep-learning backends.</p><p id="everyday-building">Some projects are smaller and more personal: connecting Tessie, Poke, and Notion for useful alerts and trip summaries. They’re experiments in making everyday software fit the way I work. <a href="/media#writing">Read the public building notes.</a></p><p>The software record also includes work across web and mobile frontends, Flask and Django backends, cloud infrastructure, and continuous-integration workflows. Public contributions include the MONAI tutorials and OpenHands projects.</p><div className="inline-links"><a href="/collection/engineering-projects">All engineering projects</a><a href="https://github.com/Project-MONAI/tutorials/pull/1129">MONAI contribution</a><a href="https://github.com/OpenHands/OpenHands/pull/731">OpenHands contribution</a></div></div><div className="engineering-notes"><PagePhoto asset={photos['projects-00']} caption="An early automated prosthetic-hand prototype" /><PagePhoto asset={photos['projects-02']} caption="Computer-vision recycling sorter · SPARK Hackathon project" /><article><span className="meta">Robotics</span><h3>From programming to mentorship</h3><p>FRC Team 4939 programming and outreach, followed by lead mentorship with Robotique Zone01.</p></article><article><span className="meta">Simulation</span><h3>Understanding systems in motion</h3><p>Formula One lap-time modelling, driving agents, race strategy, vehicle controls, and custom dashboards.</p></article><article><span className="meta">Fabrication</span><h3>From image to object</h3><p>3D printing, prosthetic prototyping, and medical-image-to-phantom workflows.</p></article></div></div></section>
<RelatedMedia path="/software" />
</> }

function BeyondPage() { return <>
  <PageIntro eyebrow="Beyond the lab" title={<>Different worlds.<br /><em>The same curiosity.</em></>}><p>Motorsport, riding, diving, music, building, and teaching. A few of the other threads that have shaped the way I learn and work.</p></PageIntro>
  <SectionNav items={[{id:'race-engineering',label:'Motorsport'}, {id:'outdoors',label:'Outdoors'}, {id:'music',label:'Music'}, {id:'community',label:'Teaching & community'}]} />
  <section className="wrap detail-section recent-stories" aria-labelledby="recent-stories-title"><div className="section-heading"><h2 id="recent-stories-title">A few moments<br /><em>beyond the lab.</em></h2><p>Music, friendship, and time outside.</p></div><div className="recent-story-grid"><article><figure><img src="/assets/stories/community-music-2025.webp" alt="Flute and tabla players performing on a decorated community stage" width="1800" height="1013" loading="lazy" /><figcaption>Community music performance · August 26, 2025</figcaption></figure><h3>Music as a shared practice</h3><p>Flute and tabla on a community stage.</p></article><article><figure><img src="/assets/stories/outdoor-gathering-2025.webp" alt="A group gathered outdoors in front of wooded hills" width="1600" height="1200" loading="lazy" /><figcaption>Outdoor gathering · October 4, 2025</figcaption></figure><h3>Time together, outside</h3><p>An autumn afternoon with wooded hills in the distance.</p></article></div></section>
  <section className="wrap detail-section" id="race-engineering"><div className="editorial-split"><PagePhoto asset={photos['motorsports-00']} caption="Arrow McLaren internship · From my public motorsport portfolio" /><div className="prose"><span className="meta">Data & strategy · 2023</span><h2>Precision,<br /><em>at race pace.</em></h2><p>At Arrow McLaren IndyCar, I worked as a data-and-strategy intern in Indianapolis. The work included deterministic strategy-prediction simulation, computer-vision and AI analysis pipelines, and race-weekend telemetry analysis supporting race and performance engineers.</p><p>Trackside exposure and shadowing systems engineers connected the code with its operating environment: real vehicles, changing conditions, and decisions that have to happen on time.</p><SourceLink href="https://www.linkedin.com/posts/udbhav-ram-engineering-and-medicine_mclaren-indycar-datascience-activity-7099432415638548481-wRsm">Read my internship retrospective</SourceLink></div></div><div className="photo-triptych">{[
  [imageAssets.macFormulaSae,'MAC Formula SAE Electric','Software, vehicle controls, dynamics, and custom dashboard work.'],
  [imageAssets.formulaLgb,'Formula LGB 1300','Test and development driving with Momentum Motorsports.'],
  [imageAssets.vwPoloCup,'Volkswagen Polo Cup','Test-driving experience with MRF at Madras International Circuit.'],
].map(([asset,title,text])=><article key={String(title)}><PagePhoto asset={asset as ImageAsset} caption={String(title)} /><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div><div className="quiet-callout"><p>In May 2023, I drove a Formula LGB 1300 with Momentum Motorsports at Madras International Circuit. Three onboard runs capture that test-driving experience alongside the engineering work.</p><a href="/media#video-GNboj6JfDeI">Watch the onboard runs →</a></div><a className="text-link" href="/collection/motorsports">Explore the motorsport record</a></section>
  <section className="detail-band" id="outdoors"><div className="wrap"><div className="section-heading"><h2>A little further<br /><em>outside.</em></h2><p>My earlier activities include experiences in the water, on horseback, on the ice, and in flight training. They are part of the journey rather than a claim about what I do every week today.</p></div><div className="interest-columns"><article><span className="meta">In the water</span><h3>Scuba diving</h3><p>I’m a PADI Advanced Open Water Diver and Enriched Air Diver (Nitrox), with both qualifications confirmed in May 2025. My earlier SSI Open Water Diver qualification was issued in June 2023 through SaltyBoneDivers in Chennai.</p><p>Diving gives me another way to explore through preparation, observation, and practice.</p></article><article><span className="meta">In the saddle</span><h3>Equestrian riding</h3><p>My riding background includes English and Western disciplines. The earlier portfolio documents years of riding experience and equestrian-community involvement.</p></article><article><span className="meta">Learning new movement</span><h3>Hockey, yoga & flight</h3><p>Ice hockey, yoga practice and instruction, and training at Brampton Flight Centre are also part of that history. Flight training is listed as an experience; a completed private-pilot licence is not claimed.</p></article></div><div className="personal-gallery outdoors-gallery">{['activities-10','activities-07'].map(id=><PagePhoto key={id} asset={photos[id as keyof typeof photos]} caption={photos[id as keyof typeof photos].caption} />)}</div><a className="text-link" href="/collection/activities-service">Training, sport & activities</a></div></section>
  <section className="wrap detail-section" id="music"><div className="section-heading"><h2>A musical<br /><em>thread.</em></h2><p>Music has been another part of my life alongside science, across Western and Indian classical traditions.</p></div><div className="personal-gallery music-gallery">{['activities-12','activities-14','activities-15'].map(id=><PagePhoto key={id} asset={photos[id as keyof typeof photos]} caption={photos[id as keyof typeof photos].caption} />)}</div><div className="music-list"><article><span>01</span><div><h3>Violin, in two traditions</h3><p>Western classical violin, including the Central Peel Regional Strings Program, and Carnatic violin. Both appear in the earlier portfolio as long-running musical practices.</p></div></article><article><span>02</span><div><h3>Piano</h3><p>Royal Conservatory of Music piano training and competition recognition form another part of the musical record.</p></div></article><article><span>03</span><div><h3>Carnatic voice</h3><p>Indian classical vocal music and performance, alongside instrumental study.</p></div></article></div><SourceLink href="https://sites.google.com/view/udbhav-ram/activities">Original music and activities record</SourceLink></section>
  <section className="detail-band" id="community"><div className="wrap prose reading-width"><h2>Sharing what<br /><em>I’ve learned.</em></h2><p>Teaching and mentorship run through several of these interests. Robotics mentorship offered a way to share programming and building; French-language STEM coordination brought an in-house curriculum into a school-board setting; yoga instruction brought another kind of practice into community and university spaces.</p><p>Institutional ambassadorship and hospital volunteering belong to this thread too. They sit beside research and engineering as ways to participate in a wider community.</p><div className="inline-links"><a href="/about#mentorship">Mentorship & institutional work</a><a href="/collection/activities-service">The full service record</a><a href="/collection/recognition">Arts, training & recognition</a></div></div></section>
<RelatedMedia path="/beyond" />
</> }

function LibraryPage() {
 const params=new URLSearchParams(window.location.search)
 const [query,setQuery]=useState(params.get('q')??'')
 const [topic,setTopic]=useState(params.get('topic')??'all')
 const [page,setPage]=useState(()=>Math.max(1,Number.parseInt(params.get('page')??'1',10)||1))
 const term=query.trim().toLowerCase()
 const entries=portfolioCollections.flatMap(c=>c.groups.flatMap((g,gi)=>g.items.map((item,ii)=>({...item,collection:c,group:g.title,id:item.id??recordId(gi,ii)}))))
 const filtered=entries.filter(e=>(topic==='all'||e.collection.id===topic||(topic==='presentations'&&Boolean(e.presentationId)))&&(!term||[e.title,e.detail,e.meta,e.note,e.group,e.collection.title].join(' ').toLowerCase().includes(term)))
 const searching=Boolean(term)||topic!=='all'
 const pages=Math.ceil(filtered.length/12)
 const currentPage=Math.min(page,Math.max(1,pages))
 useEffect(()=>{const p=new URLSearchParams();if(query)p.set('q',query);if(topic!=='all')p.set('topic',topic);if(currentPage>1)p.set('page',String(currentPage));window.history.replaceState(null,'',`/collection${p.size?'?'+p.toString():''}`)},[query,topic,currentPage])
 return <><PageIntro eyebrow="The collection" title={<>Every chapter<br /><em>has a place.</em></>}><p>{portfolioItemCount} records across the historical portfolio and the reconciled presentation inventory, organized by topic. Explore research, engineering, motorsport, service, recognition, and media, with the original context and source links preserved.</p></PageIntro><section className="wrap library-controls"><label htmlFor="collection-search">Search the collection</label><div className="search-input"><MagnifyingGlass /><input id="collection-search" type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Try scuba, robotics, Ethos, or violin…" />{query&&<button onClick={()=>{setQuery('');setPage(1)}}>Clear</button>}</div><div className="topic-filter"><label htmlFor="collection-topic">Topic</label><select id="collection-topic" value={topic} onChange={e=>{setTopic(e.target.value);setPage(1)}}><option value="all">All topics</option><option value="presentations">Presentations & talks</option>{portfolioCollections.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></div><p role="status">{searching?`${filtered.length} matching ${filtered.length===1?'entry':'entries'}`:'Choose a chapter, or search across the entire collection.'}</p></section>
 {searching?<section className="wrap search-results" aria-label="Search results">{filtered.slice((currentPage-1)*12,currentPage*12).map(e=><article key={`${e.collection.id}-${e.id}`}><span className="meta">{e.collection.title} · {e.group}</span><h2><a href={e.presentationId?`/publications#${e.presentationId}`:`/collection/${e.collection.id}#${e.id}`}>{e.title}</a></h2>{e.meta&&<p className="entry-meta">{e.meta}</p>}{e.detail&&<p>{e.detail}</p>}{e.note&&<p className="record-note">{e.note}</p>}</article>)}{filtered.length===0&&<div className="empty-results"><h2>No entries found.</h2><p>Try a broader topic, or clear the search to explore the collection.</p><button onClick={()=>{setQuery('');setTopic('all');setPage(1)}}>Reset search</button></div>}{pages>1&&<nav className="pagination" aria-label="Search results pages"><button disabled={currentPage===1} onClick={()=>{setPage(currentPage-1);document.getElementById('collection-search')?.scrollIntoView()}}>Previous</button><span>Page {currentPage} of {pages}</span><button disabled={currentPage===pages} onClick={()=>{setPage(currentPage+1);document.getElementById('collection-search')?.scrollIntoView()}}>Next</button></nav>}</section>:<div className="wrap collection-index">{portfolioCollections.map((c,i)=><a href={`/collection/${c.id}`} key={c.id}><span className="meta">0{i+1} · {c.groups.reduce((n,g)=>n+g.items.length,0)} entries</span><h2>{c.title}</h2><p>{c.summary}</p><span className="text-link">Explore this chapter</span></a>)}</div>}
 <aside className="wrap library-note"><h3>Reading the historical record</h3><p>Older affiliations, goals, experience totals, and certifications describe the period in which they were recorded. Current education and recent work live on the <a href="/about">biography</a> and <a href="/research">research</a> pages. Historical entries do not imply a current appointment, licence, or clinical qualification.</p></aside></>
}
function CollectionPage({ collection:c }: {collection:PortfolioCollection}) { return <>{c.id==='media' && <aside className="wrap quiet-callout"><p>The media collection has a new home, with grouped coverage, recordings, and links into the work.</p><a href="/media">Explore media & stories →</a></aside>}<PageIntro eyebrow="From the collection" title={c.title}><p>{c.summary}</p><a className="text-link" href="/collection">Browse or search all {portfolioItemCount} entries</a></PageIntro><SectionNav items={c.groups.map((g,i)=>({id:`group-${i}`,label:g.title}))}/><div className="wrap collection-layout"><aside><p>Historical portfolio</p><p className="small-note">Entries retain the context of the earlier site. Former roles and time-bound credentials are not presented as current.</p><SourceLink href={c.source}>Original source page</SourceLink><a href="/about">Current biography & CV</a></aside><div>{c.groups.map((g,gi)=><section className="collection-group" id={`group-${gi}`} key={g.title}><h2>{g.title}</h2>{g.items.map((item,ii)=>item.presentationId?<PresentationRecord key={item.presentationId} presentation={presentations.find(p=>p.id===item.presentationId)!}/>:<article className="record-entry" id={recordId(gi,ii)} key={`${item.title}-${ii}`} tabIndex={-1}>{item.meta&&<span className="meta">{item.meta}</span>}<h3>{item.title}</h3>{item.detail&&<p>{item.detail}</p>}{item.note&&<p className="record-note">{item.note}</p>}<div className="record-links">{item.href&&<SourceLink href={item.href}>View the original work</SourceLink>}<a href={`#${recordId(gi,ii)}`} aria-label={`Link to ${item.title}`}>Link to this entry</a></div></article>)}</section>)}</div></div><div className="wrap chapter-navigation">{portfolioCollections.filter(x=>x.id!==c.id).map(x=><a key={x.id} href={`/collection/${x.id}`}>{x.title}</a>)}</div></> }
function NotFound() { return <PageIntro eyebrow="Page not found" title="Let’s find the right chapter."><p>This page isn’t in the collection.</p><a className="button" href="/collection">Explore the collection</a></PageIntro> }

export default function DetailPages({path}:{path:string}) {
 if(path==='/media')return <MediaPage/>
 if(path==='/about')return <AboutPage/>
 if(path==='/research')return <ResearchPage/>
 if(path.startsWith('/research/'))return <StudyPage slug={path.split('/')[2]}/>
 if(path==='/publications')return <PublicationsPage/>
 if(path==='/software')return <SoftwarePage/>
 if(path==='/beyond')return <BeyondPage/>
 if(path==='/collection')return <LibraryPage/>
 if(path.startsWith('/collection/')){const c=portfolioCollections.find(c=>c.id===path.split('/')[2]);return c?<CollectionPage collection={c}/>:<NotFound/>}
 return <NotFound/>
}
const nextSteps: Record<string, { href: string; eyebrow: string; title: string; copy: string }[]> = {
 '/about': [{href:'/research',eyebrow:'Next · the questions',title:'Explore the research',copy:'See how the biography becomes clinical and technical work.'},{href:'/beyond',eyebrow:'Another side',title:'Go beyond the lab',copy:'Motorsport, music, diving, and teaching.'}],
 '/research': [{href:'/software',eyebrow:'Next · the systems',title:'Open the workbench',copy:'See the software, evidence, and operating boundaries.'},{href:'/publications',eyebrow:'Go deeper',title:'Read the record',copy:'Papers, posters, talks, and source material.'}],
 '/software': [{href:'/media#lap-companion',eyebrow:'Next · in motion',title:'Come along for a lap',copy:'A synchronized onboard companion from Madras.'},{href:'/collection?topic=engineering-projects',eyebrow:'Go deeper',title:'Browse every project',copy:'The earlier engineering record, searchable.'}],
 '/beyond': [{href:'/media#lap-companion',eyebrow:'Next · press play',title:'Watch the Formula LGB run',copy:'Onboard video with observed, time-linked notes.'},{href:'/about',eyebrow:'Back to the path',title:'Meet Udi',copy:'The people and places behind the work.'}],
 '/media': [{href:'/research',eyebrow:'Next · the work',title:'Explore the research',copy:'Move from recordings into methods and findings.'},{href:'/collection',eyebrow:'Find anything',title:'Search the collection',copy:'Every chapter in one searchable index.'}],
}
function ContextualNext(){const path=window.location.pathname.replace(/\/+$/,'')||'/';const items=nextSteps[path]??[{href:'/',eyebrow:'Start here',title:'Take the 90-second route',copy:'A short path through research, software, and life.'},{href:'/collection',eyebrow:'Or look around',title:'Search the collection',copy:'Find a person, project, talk, or interest.'}];return <aside className="contextual-next wrap" aria-label="Where to go next">{items.map(item=><a href={item.href} key={item.href}><span className="meta">{item.eyebrow}</span><h2>{item.title}</h2><p>{item.copy}</p><strong>Continue →</strong></a>)}</aside>}
export function PageFooter(){return <><ContextualNext/><footer className="page-footer wrap"><a className="brand" href="/">Udbhav Ram<span className="brand-dot">.</span></a><nav aria-label="Footer navigation"><a href="/about">About & CV</a><a href="/research">Research</a><a href="/publications">Publications & talks</a><a href="/software">Software</a><a href="/beyond">Beyond the lab</a><a href="/media">Media</a><a href="/collection">Collection</a><a href="/#contact">Contact</a></nav><div><span>© {new Date().getFullYear()} Udbhav Ram</span><span>Updated October 6, 2026</span></div></footer></>}
