import { softwareProjects } from './softwareContent'

export type SourceRecord = { label: string; href: string }

export type ExperienceRecord = {
  id: string
  institution: string
  role: string
  period: string
  category: 'Education' | 'Research' | 'Engineering' | 'Teaching & mentoring' | 'Service'
  status: 'Current' | 'Ongoing collaboration' | 'Completed' | 'Historical record'
  location?: string
  summary: string
  work: string[]
  sources: SourceRecord[]
  note?: string
}

export type ProjectRecord = {
  id: string
  title: string
  institution: string
  period: string
  category: 'Clinical research' | 'Imaging & AI' | 'Engineering' | 'Software & data' | 'Community'
  summary: string
  outcome: string
  sources: SourceRecord[]
}

export type AwardRecord = {
  id: string
  title: string
  year: string
  issuer?: string
  category: 'Personal honor' | 'Training & certification' | 'Competition' | 'Arts' | 'Feature & context'
  ownership: 'Udbhav Ram' | 'Mentor or collaborator' | 'Participation or feature'
  detail: string
  evidence: 'Primary source' | 'Historical portfolio'
  sources: SourceRecord[]
  note?: string
}

const site = 'https://sites.google.com/view/udbhav-ram'
const publicCv = '/downloads/Udbhav_Ram_Public_CV_October_2026.pdf'

export const experienceRecords: ExperienceRecord[] = [
  { id:'uw-medical-physics', institution:'University of Wisconsin–Madison', role:'PhD student, Medical Physics', period:'2026–present', category:'Education', status:'Current', location:'Madison, Wisconsin', summary:'Doctoral training at the intersection of medical imaging, AI, and radiation oncology, advised by Dr. Ran Zhang.', work:['Medical-imaging and radiation-oncology research','Vision-language models and clinically reviewed AI workflows'], sources:[{label:'UW student directory',href:'https://medphysics.wisc.edu/graduate-program/meet-our-students/'},{label:'Public CV',href:publicCv}] },
  { id:'uw-research-assistant', institution:'University of Wisconsin–Madison', role:'Research assistant, Medical Physics / Radiology', period:'June 2026–present', category:'Research', status:'Current', location:'Madison, Wisconsin', summary:'Graduate research with Dr. Ran Zhang focused on AI applications in medical imaging and radiation oncology.', work:['Radiology-specialized model evaluation','Vision-language models','Medical-imaging and radiation-oncology workflows'], sources:[{label:'ASTRO biography',href:'https://amportal.astro.org/udbhav-ram-bs-135368427'},{label:'Public CV',href:publicCv}] },
  { id:'mcmaster-medical-physics', institution:'McMaster University', role:'Honours BSc, Medical Physics with Co-op', period:'2021–2026', category:'Education', status:'Completed', location:'Hamilton, Ontario', summary:'Undergraduate training combining physics, computation, co-op placements, research, teaching, and institutional advocacy.', work:['Honours Medical Physics with Co-op','Science Co-op Student of the Year, Year 5','Research, software engineering, teaching, and student advocacy'], sources:[{label:'McMaster convocation profile',href:'https://science.mcmaster.ca/convocation-countdown-with-udbhav-ram/'},{label:'Public CV',href:publicCv}] },
  { id:'uab-research-collaborator', institution:'University of Alabama at Birmingham · Radiation Oncology', role:'Research collaborator', period:'2021–present', category:'Research', status:'Ongoing collaboration', location:'Birmingham, Alabama / remote', summary:'An undergraduate remote collaboration that continued across visiting appointments, co-op work, publications, and conference research.', work:['Abdominal CT auto-segmentation','Ethos SRS planning','TG-263 naming QA','Adaptive partial-breast contour variability'], sources:[{label:'UAB collaboration profile',href:'https://www.uab.edu/medicine/news/latest-news/mcmaster-student-and-mentor'},{label:'Public CV',href:publicCv}] },
  { id:'uab-visiting-scholar', institution:'University of Alabama at Birmingham · Radiation Oncology', role:'International visiting scholar', period:'Appointments in 2024 and 2025', category:'Research', status:'Completed', location:'Birmingham, Alabama', summary:'In-person research placements in radiation oncology built on the continuing remote collaboration.', work:['Eight-month visiting-scholar placement in 2024','Second co-op term in 2025','Clinical research, shadowing, and student outreach'], sources:[{label:'McMaster visiting-scholar profile',href:'https://news.mcmaster.ca/udbhav-ram-mcmaster-uab-international-visiting-scholar/'},{label:'Public CV',href:publicCv}] },
  { id:'juravinski', institution:'Hamilton Health Sciences · Juravinski Cancer Centre', role:'Undergraduate thesis student', period:'September 2024–May 2025', category:'Research', status:'Completed', location:'Hamilton, Ontario', summary:'A JCC–UAB commissioning study comparing 6X and 10X flattening-filter-free beams for SBRT on a TrueBeam iTX.', work:['Eclipse treatment-planning analysis','Multi-institution medical-physics collaboration','Undergraduate thesis and conference work'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier research record',href:`${site}/research`}] },
  { id:'western-lawson', institution:'Western University · Lawson Health Research Institute', role:'Researcher, Medical Physics', period:'August 2022–January 2023', category:'Research', status:'Completed', location:'London, Ontario', summary:'Computational research using optical measurements to model in-vivo hemoglobin oxygenation.', work:['Deep-learning models for real-time optical-scan analysis','Cerebral hemoglobin-oxygenation modelling'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier research record',href:`${site}/research`}] },
  { id:'st-josephs-kidney', institution:'St. Joseph’s Healthcare Hamilton · Hamilton Centre for Kidney Research', role:'Clinical research fellow, Nephrology', period:'September 2021–August 2022', category:'Research', status:'Completed', location:'Hamilton, Ontario', summary:'Biomedical research and an augmented-reality workflow for chronic-kidney-disease surgical models.', work:['Deep-learning and computer-vision tools','Augmented-reality support for 5/6 nephrectomy mouse models'], sources:[{label:'Public CV',href:publicCv},{label:'Project essay',href:'https://medium.com/@udbhavram41/how-computers-are-saving-mice-and-maybe-humans-7a8561ec6a85'}] },
  { id:'mcmaster-membrane-lab', institution:'McMaster Physics & Astronomy · Laboratory for Membrane and Protein Dynamics', role:'High school research fellow', period:'September 2019–August 2022', category:'Research', status:'Completed', location:'Hamilton, Ontario', summary:'Early biophysics and quantitative-imaging work that began before undergraduate study.', work:['Amyloid aggregation in synthetic brain membranes','Smartphone gel-electrophoresis image analysis','Coauthor on a 2020 peer-reviewed article'], sources:[{label:'Public CV',href:publicCv},{label:'PubMed article',href:'https://pubmed.ncbi.nlm.nih.gov/32981185/'}] },
  { id:'mcmaster-w-booth', institution:'McMaster University · W Booth School of Engineering Practice and Technology', role:'Research assistant', period:'January–June 2023', category:'Engineering', status:'Completed', location:'Hamilton, Ontario', summary:'Built and validated full-stack applications for academic transcript generation.', work:['JavaScript application development','Academic transcript-generation workflow','Full-stack validation'], sources:[{label:'Public CV',href:publicCv}] },
  { id:'arrow-mclaren', institution:'Arrow McLaren IndyCar', role:'Data and strategy intern', period:'June–August 2023', category:'Engineering', status:'Completed', location:'Indianapolis, Indiana', summary:'Race-strategy and performance-engineering work joining simulation, telemetry, and race-weekend decision support.', work:['Strategy simulators and modelling pipelines','Race-weekend telemetry and performance tooling','Computer-vision and AI analysis pipelines'], sources:[{label:'Internship retrospective',href:'https://www.linkedin.com/posts/udbhav-ram-engineering-and-medicine_mclaren-indycar-datascience-activity-7099432415638548481-wRsm'},{label:'Public CV',href:publicCv}] },
  { id:'mac-formula-electric', institution:'MAC Formula Electric', role:'Lead, data analytics and strategy', period:'October 2021–January 2024', category:'Engineering', status:'Completed', location:'Hamilton, Ontario', summary:'Vehicle software and analytics for McMaster’s Formula SAE Electric program.', work:['CAN communication protocols','Vehicle-control integration','Driver-dashboard systems','Data analytics and strategy'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier motorsport record',href:`${site}/motorsports`}] },
  { id:'synth-med', institution:'Synth-Med Biotechnologies', role:'Full-stack engineer', period:'2020–2021', category:'Engineering', status:'Completed', summary:'Full-stack application development for biotechnology solutions.', work:['Client and server application development','Biotechnology research and development support'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier projects record',href:`${site}/projects`}] },
  { id:'waaw', institution:'WaaW Global Inc.', role:'DevOps technical lead', period:'2020–2021', category:'Engineering', status:'Completed', summary:'Infrastructure and technical-operations leadership for an earlier software team.', work:['DevOps infrastructure','Backend and technical operations'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'jspg-ambassador', institution:'Journal of Science Policy & Governance', role:'Ambassador', period:'2022–2023', category:'Service', status:'Completed', summary:'Promoted student engagement in science policy and governance.', work:['Student outreach','Science-policy engagement'], sources:[{label:'Ambassador cohort',href:'https://www.sciencepolicyjournal.org/ambassadors.html'},{label:'Public CV',href:publicCv}] },
  { id:'physics-teaching-assistant', institution:'McMaster Physics & Astronomy', role:'Undergraduate teaching assistant', period:'September 2024–May 2025', category:'Teaching & mentoring', status:'Completed', location:'Hamilton, Ontario', summary:'Supported undergraduate instruction in introductory physics.', work:['Introductory mechanics','Electricity and magnetism','Student learning support'], sources:[{label:'Public CV',href:publicCv}] },
  { id:'physics-society-mentor', institution:'McMaster Undergraduate Physics Society', role:'Mentor', period:'September 2024–May 2025', category:'Teaching & mentoring', status:'Completed', summary:'Helped physics students navigate courses, internships, and extracurricular opportunities.', work:['Course guidance','Internship guidance','Extracurricular mentorship'], sources:[{label:'Public CV',href:publicCv}] },
  { id:'science-coop-mentor', institution:'McMaster Science Careers and Experience Centre', role:'Science Co-op mentor', period:'September 2024–May 2025', category:'Teaching & mentoring', status:'Completed', summary:'Supported medical and biological physics co-op students through placement searches.', work:['Job-search strategy','Résumé and application review','Interview preparation'], sources:[{label:'Public CV',href:publicCv},{label:'McMaster convocation profile',href:'https://science.mcmaster.ca/convocation-countdown-with-udbhav-ram/'}] },
  { id:'mcmaster-yoga', institution:'McMaster University Athletics', role:'Head yoga instructor', period:'Role began May 2022; public end date not stated', category:'Teaching & mentoring', status:'Historical record', location:'Hamilton, Ontario', summary:'Led yoga instruction for student cohorts.', work:['Yoga classes for McMaster students','Movement and practice instruction'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'anytime-yoga', institution:'Anytime Fitness Brampton', role:'Head yoga instructor', period:'Historical role; public dates not stated', category:'Teaching & mentoring', status:'Historical record', location:'Brampton, Ontario', summary:'Community yoga instruction documented in the earlier activities record.', work:['Head yoga instruction','Community fitness programming'], sources:[{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'undergraduate-ambassador', institution:'McMaster University · UAB partnership', role:'Undergraduate ambassador', period:'Undergraduate period', category:'Service', status:'Completed', summary:'Helped connect students and faculty across the UAB–McMaster research relationship.', work:['Student information sessions','Cross-institution advocacy','Program outreach'], sources:[{label:'McMaster convocation profile',href:'https://science.mcmaster.ca/convocation-countdown-with-udbhav-ram/'},{label:'UAB collaboration profile',href:'https://www.uab.edu/medicine/news/latest-news/mcmaster-student-and-mentor'}] },
  { id:'mhigh', institution:'Mary Heersink Institute for Global Health', role:'Trainee scholar', period:'Undergraduate period', category:'Service', status:'Historical record', location:'Birmingham, Alabama / Hamilton, Ontario', summary:'Student outreach and coordination supporting the UAB–McMaster relationship.', work:['Information sessions','McMaster Spring Symposium support','UAB–McMaster Summer Program coordination'], sources:[{label:'UAB collaboration profile',href:'https://www.uab.edu/medicine/news/latest-news/mcmaster-student-and-mentor'}], note:'An undergraduate trainee-scholar role.' },
  { id:'humber-river', institution:'Humber River Hospital', role:'Volunteer', period:'Historical service record', category:'Service', status:'Historical record', location:'Toronto, Ontario', summary:'Hospital service across patient-facing and operational areas.', work:['Medical imaging','Surgical inpatient services','Information services'], sources:[{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'zone01', institution:'Robotique Zone01', role:'Lead mentor', period:'Historical role; public dates not stated', category:'Teaching & mentoring', status:'Historical record', summary:'Robotics mentorship and programming leadership.', work:['Lead mentorship','Programming instruction','Team development'], sources:[{label:'Earlier projects record',href:`${site}/projects`}] },
  { id:'frc-4939', institution:'FIRST Robotics Competition Team 4939', role:'Senior programmer and outreach member', period:'Historical role; public dates not stated', category:'Teaching & mentoring', status:'Historical record', summary:'Programming and community outreach within a FIRST Robotics team.', work:['Robot programming','Team outreach','Peer technical support'], sources:[{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'sparkin-stem', institution:'Sparkin’ STEM', role:'French program coordinator', period:'Historical role; public dates not stated', category:'Teaching & mentoring', status:'Historical record', summary:'Coordinated integration of an in-house STEM curriculum with a large French-language school board.', work:['French-language curriculum coordination','STEM outreach','Program integration'], sources:[{label:'Earlier projects record',href:`${site}/projects`}] },
  { id:'uab-clinical-shadowing', institution:'UAB Radiation Oncology', role:'Clinical shadowing', period:'Completed during visiting appointments', category:'Research', status:'Completed', location:'Birmingham, Alabama', summary:'Four hundred hours of clinical shadowing with radiation oncologists and medical physicists.', work:['Radiation-oncology workflow observation','Medical-physics workflow observation'], sources:[{label:'Public CV',href:publicCv},{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'uab-hindu-yuva', institution:'UAB Hindu YUVA', role:'Community participant', period:'Historical service record', category:'Service', status:'Historical record', summary:'Participation in activities centered on Hindu values and community.', work:['Community activities','Cultural participation'], sources:[{label:'Earlier activities record',href:`${site}/activities`}] },
  { id:'formula-lgb-driver', institution:'Momentum Motorsports', role:'Formula LGB 1300 test and development driver', period:'May 2023', category:'Engineering', status:'Completed', location:'Madras International Circuit', summary:'Test-driving experience connecting vehicle behavior with engineering observation.', work:['Formula LGB 1300 test runs','Onboard video record','Driver feedback'], sources:[{label:'Earlier motorsport record',href:`${site}/motorsports`},{label:'Onboard recording',href:'/media#video-GNboj6JfDeI'}] },
  { id:'vw-polo-driver', institution:'MRF · Volkswagen Polo Cup', role:'Test driver', period:'Historical experience; public date not stated', category:'Engineering', status:'Historical record', location:'Madras International Circuit', summary:'Polo Cup test-driving experience documented in the public motorsport portfolio.', work:['Circuit test-driving','Vehicle familiarization'], sources:[{label:'Earlier motorsport record',href:`${site}/motorsports`}] },
]

const coreProjectRecords: ProjectRecord[] = [
  { id:'adaptive-breast', title:'Adaptive partial-breast contour variability', institution:'UAB Radiation Oncology', period:'2025–2026', category:'Clinical research', summary:'Interobserver analysis of target delineation in an online adaptive radiotherapy workflow.', outcome:'Presented at ASTRO 2026; the public case study distinguishes observer variability from clinical-outcomes evidence.', sources:[{label:'Case study',href:'/research/adaptive-breast-radiotherapy'},{label:'ASTRO record',href:'https://amportal.astro.org/udbhav-ram-bs-135368427'}] },
  { id:'tg263', title:'Local language models for TG-263 naming QA', institution:'UAB Radiation Oncology', period:'2025', category:'Imaging & AI', summary:'Structured prompts, rules, and local models evaluated on 1,000 radiotherapy target names.', outcome:'AAPM Blue Ribbon Poster; rule compliance improved, while meaning-preservation failures showed why clinical review remains necessary.', sources:[{label:'Case study',href:'/research/clinical-language-models'},{label:'AAPM poster',href:'https://aapm.confex.com/aapm/2025am/mediafile/Handout/Paper20105/AAPM2025_BRP_LLM.pdf'}] },
  { id:'ethos-srs', title:'Ethos 2.0 high-fidelity SRS planning', institution:'UAB Radiation Oncology', period:'2024–2025', category:'Clinical research', summary:'Forty-five-patient comparison of four planning templates for multi-metastasis single-isocenter SRS.', outcome:'First-author JACMP publication and 2024 SPS–AAPM Outstanding Poster Presentation recognition.', sources:[{label:'Case study',href:'/research/radiosurgery-planning'},{label:'PubMed',href:'https://pubmed.ncbi.nlm.nih.gov/41272935/'}] },
  { id:'auto-segmentation', title:'Abdominal CT auto-segmentation', institution:'UAB Radiation Oncology', period:'2024–2025', category:'Imaging & AI', summary:'Comparison of nnU-Net, MONAI Auto3DSeg, and SwinUNETR using geometric metrics and blinded physician review.', outcome:'First-author Intelligent Oncology publication; the two AutoML frameworks outperformed SwinUNETR and physicians preferred nnU-Net.', sources:[{label:'Case study',href:'/research/organ-segmentation'},{label:'Free full text',href:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12462693/'}] },
  { id:'brain-followup', title:'Brain-metastasis follow-up MRI', institution:'UAB Radiation Oncology', period:'2024–2025', category:'Imaging & AI', summary:'Fusion of pre-treatment contours with follow-up MRI to support post-radiotherapy assessment.', outcome:'Coauthored Neuro-Oncology Practice article; the study reported lower average review time in its evaluated cohort.', sources:[{label:'Case study',href:'/research/brain-metastases-follow-up'},{label:'Article',href:'https://academic.oup.com/nop/article/13/3/497/8382617'}] },
  { id:'beam-energy', title:'6X-FFF versus 10X-FFF for lung SBRT', institution:'Juravinski Cancer Centre · UAB', period:'Undergraduate research period', category:'Clinical research', summary:'Multi-institution dosimetric comparison of flattening-filter-free beam energies on TrueBeam iTX.', outcome:'Preserved as a source-linked research record; no clinical-outcomes claim is made.', sources:[{label:'Case study',href:'/research/lung-beam-energy'},{label:'Earlier record',href:`${site}/research`}] },
  { id:'optical-brain', title:'Optical brain-measurement modelling', institution:'Western University · Lawson', period:'Completed December 2022', category:'Imaging & AI', summary:'Machine-learning models connecting optical measurements to in-vivo hemoglobin oxygenation.', outcome:'Completed research project documented in the earlier portfolio.', sources:[{label:'Earlier record',href:`${site}/research`}] },
  { id:'kidney-ar', title:'Augmented reality for kidney-research surgical models', institution:'Hamilton Centre for Kidney Research', period:'Completed September 2023', category:'Imaging & AI', summary:'Computer-vision and AR work intended to improve accuracy in chronic-kidney-disease surgical models.', outcome:'Publicly explained in a technical essay; it is not presented as a clinical product.', sources:[{label:'Project essay',href:'https://medium.com/@udbhavram41/how-computers-are-saving-mice-and-maybe-humans-7a8561ec6a85'}] },
  { id:'amyloid', title:'Amyloid aggregation in model membranes', institution:'McMaster Physics & Astronomy', period:'2019–2020', category:'Clinical research', summary:'Study of resveratrol, caffeine, beta-carotene, EGCG, and amyloid aggregation in synthetic brain membranes.', outcome:'Coauthored peer-reviewed article in Molecular Nutrition & Food Research.', sources:[{label:'PubMed',href:'https://pubmed.ncbi.nlm.nih.gov/32981185/'},{label:'Case study',href:'/research/amyloid-membranes'}] },
  { id:'gel-analysis', title:'Smartphone gel-electrophoresis analysis', institution:'McMaster Physics & Astronomy', period:'Completed July 2021', category:'Imaging & AI', summary:'Quantitative smartphone image analysis for gel electrophoresis.', outcome:'Recorded public presentation retained with the historical project record.', sources:[{label:'Presentation',href:'https://www.youtube.com/watch?v=xW7umxU6NSM'}] },
  { id:'genomic-dose-model', title:'Genomic linear-quadratic radiation-dose modelling', institution:'UAB Radiation Oncology', period:'Undergraduate research period', category:'Imaging & AI', summary:'Exploratory machine-learning work connecting genomic inputs with linear-quadratic radiation-dose modelling.', outcome:'Preserved as exploratory research; no clinical validation or deployment is claimed.', sources:[{label:'Earlier research record',href:`${site}/research`}] },
  { id:'f1-lap-simulation', title:'Formula One lap-time simulation', institution:'McMaster University', period:'Completed December 2022', category:'Engineering', summary:'Ordinary-differential-equation modelling of factors affecting Formula One lap times.', outcome:'Completed academic modelling project with a public source document.', sources:[{label:'Project document',href:'https://drive.google.com/file/d/1o_fi4mDcXzvgSoI69mB4rgpBkePRnMiC/view'}] },
  { id:'driving-agents', title:'Driving agents in open-world simulation', institution:'Independent academic project', period:'Undergraduate period', category:'Imaging & AI', summary:'Deep-learning and computer-vision models for effective driving agents in simulation.', outcome:'Documented as exploratory simulation work.', sources:[{label:'Project document',href:'https://drive.google.com/file/d/1Q6XpC-fciEKAE5b1TU0dF3TTDitGHv8b/view?usp=sharing'}] },
  { id:'monai-contribution', title:'Project MONAI tutorials contribution', institution:'Project MONAI · open source', period:'Undergraduate period', category:'Software & data', summary:'Public contribution to NVIDIA’s Medical Open Network for AI tutorials repository.', outcome:'Merged or publicly reviewed contribution remains inspectable in the repository history.', sources:[{label:'GitHub pull request',href:'https://github.com/Project-MONAI/tutorials/pull/1129'}] },
  { id:'openhands-contribution', title:'OpenHands contribution', institution:'OpenHands · open source', period:'Undergraduate period', category:'Software & data', summary:'Public contribution to the OpenHands project, formerly All-Hands-AI.', outcome:'Contribution remains inspectable in the public repository history.', sources:[{label:'GitHub pull request',href:'https://github.com/OpenHands/OpenHands/pull/731'}] },
  { id:'strategy-simulator', title:'Race-strategy simulation', institution:'Arrow McLaren IndyCar', period:'Summer 2023', category:'Engineering', summary:'Deterministic strategy prediction and data tooling in a professional motorsport environment.', outcome:'Used within an internship spanning race, strategy, performance, and systems-engineering contexts.', sources:[{label:'Motorsport record',href:`${site}/motorsports`}] },
  { id:'formula-sae', title:'Formula SAE Electric vehicle controls', institution:'McMaster University', period:'Undergraduate period', category:'Engineering', summary:'Software, vehicle-controls, dynamics, and custom-dashboard work for MAC Formula SAE Electric.', outcome:'A hands-on bridge between software systems and vehicle behavior.', sources:[{label:'Motorsport record',href:`${site}/motorsports`}] },
  { id:'prosthetic-hand', title:'Automated prosthetic hand', institution:'Independent project', period:'Earlier project', category:'Engineering', summary:'Early prosthetic-limb prototype combining mechanical construction, wiring, and actuation.', outcome:'Documented on a dedicated public project site.', sources:[{label:'Project site',href:'https://sites.google.com/view/prostheticlimbprototype/home'}] },
  { id:'recycling-sorter', title:'Computer-vision recycling sorter', institution:'SPARK Hackathon', period:'2019', category:'Engineering', summary:'Machine-learning and computer-vision prototype for sorting recyclable material.', outcome:'SPARK Hackathon runner-up.', sources:[{label:'Earlier project record',href:`${site}/projects`}] },
  { id:'openpilot', title:'Level 2 driver-assistance conversion', institution:'Independent engineering project', period:'Earlier project', category:'Engineering', summary:'Vehicle conversion work using comma.ai and openpilot implementations.', outcome:'Public fork and project history remain available for inspection.', sources:[{label:'GitHub',href:'https://github.com/udiram/openpilot'}] },
  { id:'stem-outreach', title:'Robotics and French-language STEM outreach', institution:'Zone01 · FRC 4939 · Sparkin’ STEM', period:'Historical service record', category:'Community', summary:'Mentorship, programming leadership, and curriculum coordination across youth STEM programs.', outcome:'Combined technical instruction with widening access in English- and French-language settings.', sources:[{label:'Earlier projects record',href:`${site}/projects`},{label:'Earlier activities record',href:`${site}/activities`}] },
]

const softwareContext: Record<string, { institution: string; period: string }> = {
  'ct-forge': { institution: 'Independent research infrastructure', period: 'Active 2026' },
  protocoliq: { institution: 'Independent clinical-workflow research', period: 'Active 2026' },
  radkev: { institution: 'University of Wisconsin–Madison', period: 'Active 2026' },
  'voxelweave-designer': { institution: 'Independent imaging-to-fabrication project', period: 'Active 2026' },
  medphysbench: { institution: 'Independent medical-physics evaluation project', period: 'Active 2026' },
  'glioblastoma-analysis': { institution: 'Independent imaging-research project', period: 'Updated 2026' },
  'rsna-explorer': { institution: 'Independent conference software', period: '2026 public-program snapshot' },
  'oncoscout-2026': { institution: 'Independent conference software', period: 'ASTRO 2026 edition' },
  'aapm-2026-explorer': { institution: 'Independent conference software', period: 'AAPM 2026 edition' },
}

export const projectRecords: ProjectRecord[] = [
  ...coreProjectRecords,
  ...softwareProjects.map((project): ProjectRecord => ({
    id: `software-${project.id}`,
    title: project.name,
    institution: softwareContext[project.id].institution,
    period: softwareContext[project.id].period,
    category: 'Software & data',
    summary: project.copy,
    outcome: project.boundary,
    sources: [{ label: 'Canonical software record', href: `/software#${project.id === 'ct-forge' ? 'ct-forge' : `software-${project.id}`}` }, ...(project.href ? [{ label: project.cta ?? 'Public project', href: project.href }] : [])],
  })),
]

export const awardRecords: AwardRecord[] = [
  {id:'coop-student-year',title:'Science Co-op Student of the Year — Year 5',year:'2026',issuer:'McMaster University Faculty of Science',category:'Personal honor',ownership:'Udbhav Ram',detail:'Recognition for the UAB co-op and the broader international research and mentorship path.',evidence:'Primary source',sources:[{label:'McMaster story',href:'https://news.mcmaster.ca/udbhav-rams-co-op-supervisors-flew-in-from-alabama-to-give-him-an-award/'}]},
  {id:'aapm-blue-ribbon',title:'AAPM Blue Ribbon Poster',year:'2025',issuer:'American Association of Physicists in Medicine',category:'Personal honor',ownership:'Udbhav Ram',detail:'Designation for one of the highest-scoring AAPM 2025 abstracts, on local language models for radiotherapy naming QA.',evidence:'Primary source',sources:[{label:'AAPM abstract',href:'https://aapm.confex.com/aapm/2025am/meetingapp.cgi/Paper/20105'}]},
  {id:'ethos-course',title:'Ethos Adaptive Radiotherapy Course',year:'Historical record',issuer:'Varian Clinical School',category:'Training & certification',ownership:'Udbhav Ram',detail:'Two-and-a-half-day training program covering Ethos adaptive-radiotherapy workflows.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'employer-year',title:'Emerging Science Co-op Employer of the Year',year:'2025',issuer:'McMaster University',category:'Feature & context',ownership:'Mentor or collaborator',detail:'Carlos Cardenas received the employer award after a nomination by Udbhav Ram.',evidence:'Primary source',sources:[{label:'UAB story',href:'https://www.uab.edu/medicine/news/latest-news/cardenas-receives-mcmaster-co-op-emerging-employer-of-the-year-award'}],note:'Mentor recognition, not a personal award to Udbhav.'},
  {id:'sps-poster',title:'Outstanding Poster Presentation',year:'2024',issuer:'Society of Physics Students · AAPM',category:'Personal honor',ownership:'Udbhav Ram',detail:'Undergraduate research competition recognition for the Ethos high-fidelity SRS work.',evidence:'Primary source',sources:[{label:'AAPM newsletter',href:'https://www.aapm.org/pubs/newsletter/archive/5001.pdf'}]},
  {id:'mcmaster-feature',title:'McMaster international visiting-scholar feature',year:'2024',issuer:'McMaster University',category:'Feature & context',ownership:'Participation or feature',detail:'Institutional profile of the international visiting-scholar and UAB collaboration experience.',evidence:'Primary source',sources:[{label:'McMaster feature',href:'https://news.mcmaster.ca/udbhav-ram-mcmaster-uab-international-visiting-scholar/'}]},
  {id:'uab-feature',title:'UAB clinical-AI collaboration feature',year:'2025',issuer:'UAB Heersink School of Medicine',category:'Feature & context',ownership:'Participation or feature',detail:'Institutional profile and video coverage of the cross-border student–mentor collaboration.',evidence:'Primary source',sources:[{label:'UAB feature',href:'https://www.uab.edu/medicine/news/latest-news/mcmaster-student-and-mentor'}]},
  {id:'cupc-talk',title:'CUPC Best Talk — first place',year:'2023',issuer:'Canadian Undergraduate Physics Conference',category:'Competition',ownership:'Udbhav Ram',detail:'Recognition for a presentation on optimizing dose delivery during fractionated radiotherapy.',evidence:'Primary source',sources:[{label:'Recorded talk',href:'https://www.youtube.com/watch?v=7JgRKwVRkEo'}]},
  {id:'ap-scholar',title:'AP Scholar with Distinction',year:'Historical record',issuer:'College Board',category:'Personal honor',ownership:'Udbhav Ram',detail:'Academic recognition preserved with the title shown on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'hosa',title:'HOSA — second place nationally',year:'Historical record',issuer:'HOSA',category:'Competition',ownership:'Udbhav Ram',detail:'National competition result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'math-top-quarter',title:'Top 25% in Mathematics',year:'Historical record',category:'Personal honor',ownership:'Udbhav Ram',detail:'Mathematics recognition preserved with its original historical wording; the earlier page does not name the issuer.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'yoga-teacher',title:'Certified yoga teacher',year:'2018',category:'Training & certification',ownership:'Udbhav Ram',detail:'Yoga teacher training associated with later instruction at Anytime Fitness Brampton and McMaster University.',evidence:'Historical portfolio',sources:[{label:'Earlier activities page',href:`${site}/activities`}]},
  {id:'french-certification',title:'French-language certification',year:'Historical record',category:'Training & certification',ownership:'Udbhav Ram',detail:'French-language credential listed on the earlier awards page; the public record does not name the issuer.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'chess-champion',title:'Provincial chess champion',year:'Historical record',category:'Competition',ownership:'Udbhav Ram',detail:'Provincial championship listed on the earlier awards page; the public record does not name the event organizer.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'medical-youth',title:'Medical Youth Summer Program',year:'Historical record',category:'Training & certification',ownership:'Participation or feature',detail:'Program participation listed in the earlier awards and certifications record.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'mirai',title:'The Mirai Project — runner-up',year:'2020',issuer:'The Mirai Project',category:'Competition',ownership:'Udbhav Ram',detail:'Runner-up result in a medical case-study competition.',evidence:'Historical portfolio',sources:[{label:'Earlier projects page',href:`${site}/projects`}]},
  {id:'computer-science',title:'Computer Science competency',year:'Historical record',category:'Training & certification',ownership:'Udbhav Ram',detail:'Computer-science competency credential listed on the earlier awards page; the public record does not name the issuer.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'cpr-first-aid',title:'CPR, First Aid, and AED certification',year:'Historical record',category:'Training & certification',ownership:'Udbhav Ram',detail:'Safety training listed on the earlier awards page; current validity and issuer are not stated.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'piano-bronze',title:'Five-time piano bronze medalist',year:'Historical record',category:'Arts',ownership:'Udbhav Ram',detail:'Five bronze-medal results listed in the earlier arts record.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'piano-silver',title:'Three-time piano silver medalist',year:'Historical record',category:'Arts',ownership:'Udbhav Ram',detail:'Three silver-medal results listed in the earlier arts record.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'piano-gold',title:'Three-time piano gold medalist',year:'Historical record',category:'Arts',ownership:'Udbhav Ram',detail:'Three gold-medal results listed in the earlier arts record.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'robotics-mentor',title:'Robotics lead mentor recognition',year:'Historical record',category:'Feature & context',ownership:'Participation or feature',detail:'Lead-mentor recognition connected to robotics instruction and community work.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'spelling-bee',title:'GRAMEN Spelling Bee semifinalist',year:'Historical record',issuer:'GRAMEN Spelling Bee',category:'Competition',ownership:'Udbhav Ram',detail:'Semifinalist result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'karting-runner-up',title:'Go-karting provincial runner-up',year:'Historical record',category:'Competition',ownership:'Udbhav Ram',detail:'Provincial runner-up result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'badminton-runner-up',title:'Badminton provincial runner-up',year:'Historical record',category:'Competition',ownership:'Udbhav Ram',detail:'Provincial runner-up result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'robotics-runner-up',title:'Robotics provincial runner-up',year:'Historical record',category:'Competition',ownership:'Udbhav Ram',detail:'Provincial runner-up result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'frc-semifinalist',title:'FIRST Robotics Competition semifinalist',year:'Historical record',issuer:'FIRST Robotics Competition',category:'Competition',ownership:'Udbhav Ram',detail:'Semifinalist result listed on the earlier awards page.',evidence:'Historical portfolio',sources:[{label:'Earlier awards page',href:`${site}/awards-and-certifications`}]},
  {id:'spark-runner-up',title:'SPARK Hackathon runner-up',year:'2019',issuer:'SPARK Hackathon',category:'Competition',ownership:'Udbhav Ram',detail:'Runner-up result for a computer-vision and machine-learning recycling sorter.',evidence:'Historical portfolio',sources:[{label:'Earlier projects page',href:`${site}/projects`}]},
  {id:'padi-advanced-open-water',title:'PADI Advanced Open Water Diver',year:'2025',issuer:'PADI',category:'Training & certification',ownership:'Udbhav Ram',detail:'Advanced Open Water qualification confirmed by the site owner in May 2025.',evidence:'Historical portfolio',sources:[{label:'Activities and training record',href:'/collection/activities-service#entry-1-0'}]},
  {id:'padi-enriched-air',title:'PADI Enriched Air Diver (Nitrox)',year:'2025',issuer:'PADI',category:'Training & certification',ownership:'Udbhav Ram',detail:'Enriched Air Diver qualification confirmed by the site owner in May 2025.',evidence:'Historical portfolio',sources:[{label:'Activities and training record',href:'/collection/activities-service#entry-1-0'}]},
  {id:'ssi-open-water',title:'SSI Open Water Diver',year:'2023',issuer:'SSI · SaltyBoneDivers',category:'Training & certification',ownership:'Udbhav Ram',detail:'Open Water qualification issued June 3, 2023, through SaltyBoneDivers in Chennai.',evidence:'Historical portfolio',sources:[{label:'Activities and training record',href:'/collection/activities-service#entry-1-0'},{label:'Earlier activities page',href:`${site}/activities`}]},
]
