import { useState } from 'react'
import { ArrowLeft, Play, ArrowUpRight } from '@phosphor-icons/react'
import media from './mediaContent.json'
import './MediaPage.css'
import LapCompanion from './LapCompanion'
import SaveButton from './SaveButton'

const date = (value: string) => new Date(`${value.length === 7 ? value + '-01' : value}T12:00:00Z`).toLocaleDateString('en-US', { month: 'long', ...(value.length === 10 ? { day: 'numeric' } : {}), year: 'numeric', timeZone: 'UTC' })
const destinations: Record<string, string> = {
  '/about#recognition-about': 'Recognition', '/about#mentorship': 'Mentorship & exchange', '/about#biography': 'Biography', '/about#timeline': 'Education & experience',
  '/beyond': 'Beyond the lab', '/beyond#race-engineering': 'Motorsport', '/research': 'Research stories', '/software': 'Software & building', '/publications#presentations': 'Presentation record',
  '/research/adaptive-breast-radiotherapy': 'Adaptive radiotherapy', '/research/radiosurgery-planning': 'Radiosurgery planning', '/research/clinical-language-models': 'Clinical language models', '/research/organ-segmentation': 'Organ segmentation', '/research/lung-beam-energy': 'Beam-energy study',
  '/collection/motorsports': 'Motorsport archive', '/collection/research-record': 'Research archive', '/collection/engineering-projects': 'Engineering archive', '/collection/activities-service': 'Service archive',
}
function Connections({ pages }: { pages: string[] }) { return <div className="media-connections"><span>Follow the story</span>{pages.slice(0, 3).map(p => <a href={p} key={p}>{destinations[p] ?? 'Explore the related work'} →</a>)}</div> }

function Video({ video: v }: { video: typeof media.videos[number] }) {
  const [loaded, setLoaded] = useState(false)
  return <article className="media-video" id={v.id} tabIndex={-1} data-media-video>
    <div className={`video-stage video-${v.topic === 'Motorsport' ? 'driving' : 'talk'}`}>
      {loaded ? <iframe src={v.embed_url} title={v.title} allow="encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /> : <button className="video-load" onClick={() => setLoaded(true)} aria-label={`Load YouTube video: ${v.title}`}><img src={`/assets/media/video-thumbnails/${v.video_id}.jpg`} alt="" width="480" height="360" loading="lazy" /><span><Play size={32} weight="fill" /><b>Load video</b><small>{v.duration} · YouTube</small></span></button>}
    </div>
    <div className="video-caption"><span className="meta">{v.topic} · {v.duration}</span><h3>{v.title}</h3><p>{v.summary}</p><p className="media-date">Uploaded {date(v.upload_date)}{v.event_date && <><br />{v.topic === 'Motorsport' ? 'Driven' : 'Event'}: {date(v.event_date)}</>}</p><div className="card-actions"><a className="text-link" href={v.url}>Watch on YouTube <ArrowUpRight /></a><SaveButton id={`media:video:${v.id}`} compact /></div>{loaded && <button className="video-unload" onClick={() => setLoaded(false)}>Close video</button>}<Connections pages={v.related_pages} /></div>
  </article>
}

export function RelatedMedia({ path }: { path: string }) {
  const videos = media.videos.filter(v => v.related_pages.some(p => p.split('#')[0] === path)).slice(0, 2)
  const article = media.articles.find(a => a.related_pages.some(p => p.split('#')[0] === path))
  if (!videos.length && !article) return null
  return <aside className="wrap media-related"><span className="meta">Another way into the story</span><h2>Read it. <em>Hear it.</em></h2><div>{article && <a href={`/media#${article.id}`}><span>In print · {article.publisher}</span><strong>{article.title}</strong></a>}{videos.map(v => <a key={v.id} href={`/media#${v.id}`}><span>Watch · {v.duration}</span><strong>{v.title}</strong></a>)}</div><a className="text-link" href="/media">All coverage & videos →</a></aside>
}

export default function MediaPage() {
  const [topic, setTopic] = useState('All videos')
  const [query, setQuery] = useState('')
  const videos = media.videos.filter(v => (topic === 'All videos' || v.topic === topic) && `${v.title} ${v.summary}`.toLowerCase().includes(query.toLowerCase().trim()))
  const groups = [...new Set(media.articles.map(a => a.story_group))].map(group => media.articles.filter(a => a.story_group === group)).sort((a,b) => b[0].published_date.localeCompare(a[0].published_date))
  return <>
    <div className="page-intro wrap"><a className="back-link" href="/"><ArrowLeft /> Home</a><span className="meta page-eyebrow">Media & stories</span><h1>A few windows<br />into <em>my world.</em></h1><div className="page-lede"><p>Profiles, conversations, and recordings from research, student exchange, and life beyond the lab. Read a story, hear the work in my own words, or come along for a lap.</p></div></div>
    <nav className="section-nav wrap" aria-label="On this page"><span>Explore</span><a href="#coverage">Articles & interviews</a><a href="#videos">Videos</a><a href="#writing">Writing</a><a href="#profiles">Institutional profiles</a></nav>
    <section className="wrap media-feature"><figure className="page-photo"><img src="/assets/optimized/coop-award.webp" alt="Udi receiving the McMaster Science Co-op Student of the Year award" width="1000" height="750" /><figcaption>McMaster Science Co-op Student of the Year · <a href={media.articles[0].url}>McMaster story & photograph</a></figcaption></figure><div><span className="meta">Research, and the people behind it</span><h2>A moment<br /><em>worth flying for.</em></h2><p>My UAB supervisors travelled from Alabama to McMaster for a co-op award presentation. The story is also about the exchange, friendships, and student mentorship that grew around the research.</p><a className="text-link" href={media.articles[0].url}>Read the McMaster profile <ArrowUpRight /></a></div></section>
    <section className="wrap detail-section" id="coverage"><div className="section-heading"><h2>In print,<br /><em>in conversation.</em></h2><p>Nine article editions and mentions across six story groups. Original and adapted editions appear together; award mentions are labelled separately from interviews.</p></div><div className="coverage-list">{groups.map(articles => { const a=articles[0]; return <article className="coverage-story" id={a.id} tabIndex={-1} key={a.id} data-media-article><div className="coverage-meta"><span className="meta">{a.kind === 'q-and-a' ? 'Q&A' : a.kind === 'award-mention' ? 'Award mention' : a.story_group === 'employer-recognition-2025' ? 'Mentorship & employer recognition' : 'Profile'}</span><span>{a.date_label ?? date(a.published_date)}</span><span>{a.publisher}</span></div><div><h3><a href={a.url}>{a.title}</a></h3><p>{a.summary}</p>{a.date_note && <p className="media-note">{a.date_note}</p>}<div className="card-actions"><a className="text-link" href={a.url}>Read the {a.kind === 'award-mention' ? 'newsletter mention' : 'story'} <ArrowUpRight /></a><SaveButton id={`media:article:${a.story_group}`} compact /></div>{articles.slice(1).map(other => <div className="media-edition" id={other.id} tabIndex={-1} key={other.id} data-media-article><span className="meta">{other.kind === 'original-edition' ? 'Original edition · same story' : 'Related coverage · same award'}</span><a href={other.url}>{other.title}</a><small>{other.publisher} · {date(other.published_date)}</small></div>)}<Connections pages={a.related_pages} /></div></article>})}</div></section>
    <LapCompanion />
    <section className="detail-band" id="videos"><div className="wrap"><div className="section-heading"><h2>Press play.<br /><em>Stay curious.</em></h2><p>Fifteen public videos, from research presentations to three Formula LGB runs filmed in May 2023 and uploaded in September 2026. Upload dates describe publication, not proof of attendance or delivery.</p></div><p className="video-privacy">Preview images are served by this site. Videos connect to YouTube only when you choose “Load video”. Titles and summaries follow the public metadata; these are not full transcript reviews.</p><div className="media-controls"><label htmlFor="media-search">Find a video<input id="media-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try segmentation, UAB, or Arduino" /></label><label htmlFor="media-topic">Topic<select id="media-topic" aria-label="Topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['All videos','Research','Exchange & mentorship','Motorsport','Building'].map(t=><option key={t}>{t}</option>)}</select></label></div><p className="media-result-count" role="status">{videos.length} of {media.videos.length} videos</p><div className="media-video-grid">{videos.map(v=><Video key={v.id} video={v}/>)}</div>{!videos.length && <div className="empty-results"><h3>No videos match that search.</h3><button onClick={()=>{setQuery('');setTopic('All videos')}}>Reset video filters</button></div>}</div></section>
    <section className="wrap detail-section media-writing" id="writing"><div><span className="meta">In my own words</span><h2>Notes from<br /><em>the workbench.</em></h2></div><div>{media.writing.map(w=><article key={w.id} id={`writing-${w.id}`} tabIndex={-1}><span className="meta">{w.publisher} · {date(w.published_date)}</span><h3><a href={w.url}>{w.title}</a></h3><p>An essay from my earlier research. The original link is preserved; access on Medium may vary.</p><SaveButton id={`media:writing:${w.id}`} compact /></article>)}<article><span className="meta">X · July 24, 2026</span><h3><a href="https://x.com/UdbhavRam/status/2080675842980557111">Building the AAPM 2026 Explorer</a></h3><p>A retrospective on an independent conference-program tool, with search and calendar features.</p><a href="/software#conference-tools">Explore the conference tools →</a></article><article><span className="meta">X · June 28, 2026</span><h3><a href="https://x.com/UdbhavRam/status/2071427843754463536">Personal telemetry and useful automations</a></h3><p>Small experiments connecting Tessie, Poke, and Notion for alerts and trip summaries.</p><a href="/software#everyday-building">More everyday building →</a></article></div></section>
    <section className="wrap detail-section" id="profiles"><div className="section-heading"><h2>Around the<br /><em>community.</em></h2><p>Institutional and conference listings offer another view of the work. Undergraduate-era roles are part of the earlier story.</p></div><div className="profile-list">{media.profiles.map(p=><article key={p.id} id={`profile-${p.id}`} tabIndex={-1}><span className="meta">{p.publisher}</span><h3><a href={p.url}>{p.title}</a></h3><p>{p.summary}</p>{p.id==='mh-high-scholar' && <p className="media-note">Undergraduate-era Trainee Scholar role.</p>}<SaveButton id={`media:profile:${p.id}`} compact /><Connections pages={p.related_pages}/></article>)}</div><p className="media-scope">Selected public sources checked October 6, 2026. This is a curated collection, not an exhaustive record of online mentions. <a href="/collection/media">Earlier media archive</a> · <a href="https://www.youtube.com/channel/UCTn6NYNbV55T4zs9v1nHOwA">YouTube channel</a></p></section>
  </>
}
